# tcp 服务器端口
logging:
  file:
    path: D:\Log
  level:
    root: info

#spring:
#  redis:
#    password: 123456
#    sentinel:
#      master: mymaster
#      nodes: 192.168.190.129:26379,192.168.190.129:26380,192.168.190.129:26381
#    lettuce:
#      pool:
#        max-idle: 10
#        max-active: 20
#        min-idle: 5
#        max-wait: 10000ms
#  data:
#    mongodb:
#      # 集群配置mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
#      uri: mongodb://192.168.204.81:27017,192.168.204.82:27017,192.168.204.83:27017/testdb?maxPoolSize=512

spring:
  dubbo:
    application:
      name: dubbo-provider
      registry: zookeeper://47.99.113.23:2181

