# tcp 服务器端口
tcp:
  server:
    port: 11211
    heartbeattime: 30

logging:
  file:
    path: D:\Log
  level:
    root: info

app:
  zk:
    switch: true
    addr: 47.99.113.23:2181
    timeout: 15000
    root: /route

route:
  url: http://localhost:8083/


spring:
  redis:
    password: 123456
    sentinel:
      master: mymaster
      nodes: 192.168.190.129:26379,192.168.190.129:26380,192.168.190.129:26381
    lettuce:
      pool:
        max-idle: 10
        max-active: 20
        min-idle: 5
        max-wait: 10000ms


