# tcp 服务器端口
tcp:
  server:
    port: 11211
    heartbeattime: 30

logging:
  file:
    path: D:\Log
  level:
    root: info

app:
  zk:
    switch: true
    addr: 47.99.113.23:2181
    timeout: 15000
    root: /route

route:
  url: http://localhost:8083/