server:
  port: 8083

spring:
  application:
    name: tcpservice-route
  profiles:
    active: dev #默认为开发环境

dubbo:
  registry:
    timeout: 15000
  scan:
    base-packages: com.xcm.tcpservice.schedule.service

